---
pipeline:
  gcr:
    image: plugins/gcr
    registry: gcr.io/html-test-253411
    repo: simple-html
    tags:
      - "${DRONE_TAG##v}"
      - "${DRONE_COMMIT_SHA}"
      - latest
    json_key:
      from_secret: gcr_credentials
  
  deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./charts/simple-html
    release: simple-html
    namespace: master
    secrets: [api_server, kubernetes_token]
    values: 
    - image.tag=${DRONE_TAG##v}
    - image.registry=gcr.io/html-test-253411
    wait: true

  trigger:
    event:
    - tag
