---
pipeline:
  gcr:
    image: plugins/gcr
    registry: gcr.io/private-47
    repo: simple-html
    tags:
      - "${DRONE_TAG##v}"
      - "${DRONE_COMMIT_SHA}"
      - latest
    json_key:
      from_secret: gcr_credentials
    when:
      event: tag
      branch: master
  
  deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./charts/simple-html
    release: simple-html
    namespace: master
    secrets: [api_server, kubernetes_token, gcr_repo]
    values: image.tag=${DRONE_COMMIT_SHA}
    wait: true
    when:
      event: tag
      branch: master

